proto tcp
port 51204
dev tap99
tls-server
proto tcp6-server

ca /root/openvpn-test-server/keys/ca.crt
cert /root/openvpn-test-server/keys/server.crt
key /root/openvpn-test-server/keys/server.key
dh /root/openvpn-test-server/keys/dh.pem

ifconfig 10.204.9.1 255.255.255.0
ifconfig-ipv6 fd00:abcd:204:9::1/64 fd00:abcd:204:9::2

keepalive 10 30

# Enable compression on the VPN link.
# If you enable it here, you must also
# enable it in the client config file.
comp-lzo

push "route 10.204.0.0 255.255.0.0 10.204.9.1"
push "route-ipv6 fd00:abcd:204::/48"
verb 4

# for 2.6 ("p2p NCP")
data-ciphers-fallback BF-CBC
data-ciphers BF-CBC:AES-256-GCM:AES-128-GCM

# COMPAT: gert, 13.11.21 compat with 2.2/2.3 clients
tls-version-min 1.0

# COMPAT: gert, 22.12.21, OpenSSL 3.0.0 / sha1 & BF-CBC 
tls-cert-profile insecure
providers legacy default
