port 51196
proto udp6

dev tap9

ca /root/openvpn-test-server/keys/ca.crt
cert /root/openvpn-test-server/keys/server.crt
key /root/openvpn-test-server/keys/server.key
dh /root/openvpn-test-server/keys/dh.pem

mode server
tls-server

# Push routes to the client to allow it
# to reach other private subnets behind
# the server.  Remember that these
# private subnets will also need
# to know to route the OpenVPN client
# address pool (10.8.0.0/255.255.255.0)
# back to the OpenVPN server.
push "route-gateway 10.204.4.1"
push "route 10.204.0.0 255.255.0.0"		# vlan 200
push "route 10.207.0.0 255.255.0.0"		# vlan 207
push "route-ipv6 fd00:abcd:204::/48"		# vlan 200
push "route-ipv6 fd00:abcd:207::/48"		# vlan 207
# this route will not work (nobody here on ::f195), but should not do
# any harm either (less specific).  Verify manually that it works.
push "route-ipv6 fd00:abcd:204::/45 fd00:abcd:204:4::f195 3000"

# Settings per client
client-config-dir ccd

keepalive 10 30

# Enable compression on the VPN link.
# If you enable it here, you must also
# enable it in the client config file.
comp-lzo

# Output a short status file showing
# current connections, truncated
# and rewritten every minute.
status openvpn-status.log

# Set the appropriate level of log
# file verbosity.
#
# 0 is silent, except for fatal errors
# 4 is reasonable for general usage
# 5 and 6 can help to debug connection problems
# 9 is extremely verbose
verb 4

explicit-exit-notify 1

client-to-client

# tagged-only mode
vlan-tagging
# no "native VLAN"
#vlan-accept tagged

# native VLAN 200, do tagged/untagged
vlan-accept all
vlan-pvid 200

# bring up tap interfaces
script-security 2
up setup-tap-tagged.sh

cipher BF-CBC        # Blowfish (for 2.2/2.3 client compat)

# COMPAT: gert, 13.11.21 compat with 2.2/2.3 clients
tls-version-min 1.0

# COMPAT: gert, 13.11.21, add BF-CBC (2.2/2.3 clients)
ncp-ciphers AES-256-GCM:AES-128-GCM:AES-256-CBC:BF-CBC

# COMPAT, gert, 15.11.21, add fallback cipher (2.3 / --enable small, no OCC)
data-ciphers-fallback BF-CBC

# COMPAT: gert, 22.12.21, OpenSSL 3.0.0 / sha1 & BF-CBC 
tls-cert-profile insecure
providers legacy default
