FROM docker.io/ubuntu:24.04@sha256:534baea6a22c03a63003dbc8dbe78fe34bc0d7e595d9a9dc9834884ff530eb55

COPY prepare-openvpn-build.sh /build/
COPY create-openvpn-executable.sh /build/

RUN /build/prepare-openvpn-build.sh

WORKDIR /build/openvpn
RUN /build/create-openvpn-executable.sh release/2.6 26
RUN /build/create-openvpn-executable.sh release/2.7 27
RUN /build/create-openvpn-executable.sh master master

WORKDIR /home/ubuntu

RUN bash -c 'echo "Available OpenVPN versions:"; ls /usr/local/bin|cat'
