FROM docker.io/ubuntu:14.04

COPY prepare-openvpn-build.sh /build/
COPY create-openvpn-executable.sh /build/

RUN /build/prepare-openvpn-build.sh

WORKDIR /build/openvpn
RUN /build/create-openvpn-executable.sh release/2.2 22
RUN /build/create-openvpn-executable.sh release/2.3 23

RUN bash -c 'echo "Available OpenVPN versions:"; ls /usr/local/bin|cat'
