FROM docker.io/ubuntu:24.04@sha256:008173c23f95b170204355c12626cb5a965d779a7e1283b09e9cffbb1bf33ca3

COPY prepare-openvpn-build.sh /build/
COPY create-openvpn-executable.sh /build/

RUN /build/prepare-openvpn-build.sh

WORKDIR /build/openvpn
RUN /build/create-openvpn-executable.sh release/2.6 26
RUN /build/create-openvpn-executable.sh release/2.7 27
RUN /build/create-openvpn-executable.sh master master

WORKDIR /home/ubuntu

RUN bash -c 'echo "Available OpenVPN versions:"; ls /usr/local/bin|cat'
