FROM docker.io/ubuntu:14.04.5@sha256:30204139c6ab96ebd75d72f34db390f28c4decd5e563488b4e485bf979397b67

COPY prepare-openvpn-build.sh /build/
COPY create-openvpn-executable.sh /build/

RUN /build/prepare-openvpn-build.sh

WORKDIR /build/openvpn
RUN /build/create-openvpn-executable.sh release/2.2 22
RUN /build/create-openvpn-executable.sh release/2.3 23

WORKDIR /home/ubuntu

RUN bash -c 'echo "Available OpenVPN versions:"; ls /usr/local/bin|cat'
