FROM docker.io/ubuntu:14.04@sha256:64483f3496c1373bfd55348e88694d1c4d0c9b660dee6bfef5e12f43b9933b30

COPY prepare-openvpn-build.sh /build/
COPY create-openvpn-executable.sh /build/

RUN /build/prepare-openvpn-build.sh

WORKDIR /build/openvpn
RUN /build/create-openvpn-executable.sh release/2.2 22
RUN /build/create-openvpn-executable.sh release/2.3 23

WORKDIR /home/ubuntu

RUN bash -c 'echo "Available OpenVPN versions:"; ls /usr/local/bin|cat'
