FROM docker.io/ubuntu:24.04@sha256:a853f94d226358a79c740cfc7bce0c289748f3fe3488d921d038ccd752c61b60

COPY prepare-openvpn-build.sh /build/
COPY create-openvpn-executable.sh /build/

RUN /build/prepare-openvpn-build.sh

WORKDIR /build/openvpn
RUN /build/create-openvpn-executable.sh release/2.6 26
RUN /build/create-openvpn-executable.sh release/2.7 27
RUN /build/create-openvpn-executable.sh master master

WORKDIR /home/ubuntu

RUN bash -c 'echo "Available OpenVPN versions:"; ls /usr/local/bin|cat'
