port 51194
proto tcp6-server
dev tun

ca /root/openvpn-test-server/keys/ca.crt
cert /root/openvpn-test-server/keys/server.crt
key /root/openvpn-test-server/keys/server.key
dh /root/openvpn-test-server/keys/dh.pem

# Configure server mode and supply a VPN subnet
# for OpenVPN to draw client addresses from.
# The server will take 10.8.0.1 for itself,
# the rest will be made available to clients.
# Each client will be able to reach the server
# on 10.8.0.1. Comment this line out if you are
# ethernet bridging. See the man page for more info.
server 10.204.1.0 255.255.255.0
server-ipv6 fd00:abcd:204:1::/64

# Maintain a record of client <-> virtual IP address
# associations in this file.  If OpenVPN goes down or
# is restarted, reconnecting clients can be assigned
# the same virtual IP address from the pool that was
# previously assigned.
ifconfig-pool-persist ipp.txt 60

# new default topolgy in 2.7 -> this test needs net30 (ipp.txt)
topology net30

# Push routes to the client to allow it
# to reach other private subnets behind
# the server.  Remember that these
# private subnets will also need
# to know to route the OpenVPN client
# address pool (10.8.0.0/255.255.255.0)
# back to the OpenVPN server.
push "route 10.204.0.0 255.255.0.0"
push "route-ipv6 fd00:abcd:204::/48"

keepalive 10 30

# Enable compression on the VPN link.
# If you enable it here, you must also
# enable it in the client config file.
comp-lzo

# Output a short status file showing
# current connections, truncated
# and rewritten every minute.
status openvpn-status.log

# Set the appropriate level of log
# file verbosity.
#
# 0 is silent, except for fatal errors
# 4 is reasonable for general usage
# 5 and 6 can help to debug connection problems
# 9 is extremely verbose
verb 4

cipher BF-CBC        # Blowfish (for 2.2/2.3 client compat)

# allow lots of ciphers, including "none" and "DES-EDE3-CBC", test case _1x etc
# COMPAT: gert, 13.11.21, add BF-CBC
#ncp-ciphers AES-256-GCM:AES-128-GCM:AES-128-CBC:AES-192-CBC:AES-256-CBC:none:DES-EDE3-CBC
ncp-ciphers AES-256-GCM:AES-128-GCM:AES-128-CBC:AES-192-CBC:AES-256-CBC:none:DES-EDE3-CBC:BF-CBC

# COMPAT: gert, 13.11.21 compat with 2.2/2.3 clients
tls-version-min 1.0

# COMPAT, gert, 15.11.21, add fallback cipher (2.3 / --enable small, no OCC)
data-ciphers-fallback BF-CBC

# COMPAT: gert, 22.12.21, OpenSSL 3.0.0 / sha1 & BF-CBC 
tls-cert-profile insecure
providers legacy default

# FEAT: gert, 25.12.24, port-share with v6
# MASTER ONLY
port-share ::1 80 /var/www/ps
##26 port-share 127.0.0.1 80 /var/www/ps
