# openvpn "tap base" to t_server tap-udp-p2mp instance
#
# this is permanently up and gets pinged by the t_server->t_client tests
#
# (*this* instance actually is not excercising --iroute, because it's
# a tap instance, excercising vlan assignment on the server)
#
# keys+ca.crt referenced here need to match "the server instances"
#
client
ca /home/openvpn-keys/ca.crt
cert /home/openvpn-keys/client.crt
key /home/openvpn-keys/client.key
remote-cert-tls server
nobind
comp-lzo
verb 3
dev tap
proto udp
remote REMOTE 51196
connect-retry 1 5
keepalive 10 30
persist-tun
persist-key

# "cipher in ccd" test (server: tap-udp-p2mp/ccd/tserver-anchor-207)
data-ciphers CAMELLIA-128-CBC:AES-256-GCM:AES-128-GCM
cipher CAMELLIA-128-CBC
