# openvpn "tap base" to gentoo(2).ov
#
# this is permanently up and gets pinged by the t_server->t_client tests
#
# (*this* instance actually is not excercising --iroute, because it's
# a tap instance, excercising vlan assignment on the gentoo.ov server)
#
# keys+ca.crt referenced here need to match "the server instances"
#
client
ca /home/openvpn-keys/ca.crt
cert /home/openvpn-keys/freebsd-74-amd64.crt
key /home/openvpn-keys/freebsd-74-amd64.key
remote-cert-tls server
nobind 
comp-lzo
verb 3
dev tap4
proto udp
remote gentoo.ov.greenie.net 51196
keepalive 10 30
persist-tun
persist-key

# nur auf 11 noetig
#script-security 2
#up /usr/local/etc/openvpn/inet6-no-ifdisabled.sh

# "cipher in ccd" test (server: tap-udp-p2mp/ccd/freebsd-74-amd64)
ncp-ciphers CAMELLIA-128-CBC:AES-256-GCM:AES-128-GCM
cipher CAMELLIA-128-CBC			# sonst kommt die instanz nicht hoch
