#################################################
# P2P UDP server, static key, no TLS
#################################################

# Which local IP address should OpenVPN
# listen on? (optional)
#local 195.30.36.4

# Which TCP/UDP port should OpenVPN listen on?
# If you want to run multiple OpenVPN instances
# on the same machine, use a different port
# number for each one.  You will need to
# open up this port on your firewall.
port 51204

# TCP or UDP server?
proto udp6
;proto udp

dev tun

# no TLS, just static key
secret /root/openvpn-test-server/keys/p2p-gentoo.key

# 2.7
# MASTER ONLY
allow-deprecated-insecure-static-crypto

# no "server", but topology is needed now! (GH #529)
# gert, 01.05.24, out it goes, default topology for "!server" stays net30
#topology net30
ifconfig 10.204.8.1 10.204.8.2
ifconfig-ipv6 fd00:abcd:204:8::1/64 fd00:abcd:204:8::2

# *no* keepalive is needed, we have "float" for that (and no TLS)
#keepalive 10 30
float

# Enable compression on the VPN link.
# If you enable it here, you must also
# enable it in the client config file.

# gert, 21.7.20: wir haben ein Problem mit Fragmenten, 
# ich weiss nur noch nicht wo - hilft das?
# gert, 06.04.20, es hilft, aber gibt's erst ab 2.5 -> setenv opt
setenv opt allow-compression yes

comp-lzo

# The persist options will try to avoid
# accessing certain resources on restart
# that may no longer be accessible because
# of the privilege downgrade.
persist-key
persist-tun

# Output a short status file showing
# current connections, truncated
# and rewritten every minute.
status openvpn-status.log

# 4 is reasonable for general usage
verb 4

# Silence repeating messages.  At most 20
# sequential messages of the same message
# category will be output to the log.
;mute 20

# COMPAT: gert, 13.11.21 compat with 2.2/2.3 clients
tls-version-min 1.0

# COMPAT: gert, 22.12.21, OpenSSL 3.0.0 / sha1 & BF-CBC 
#tls-cert-profile insecure
providers legacy default
