#
# INETD server
inetd nowait
dev tap99
tls-server
proto tcp-server

# Any X509 key management system can be used.
# OpenVPN can also use a PKCS #12 formatted key file
# (see "pkcs12" directive in man page).
ca /root/openvpn-test-server/keys/ca.crt
cert /root/openvpn-test-server/keys/server.crt
key /root/openvpn-test-server/keys/server.key

# Diffie hellman parameters.
# Generate your own with:
#   openssl dhparam -out dh1024.pem 1024
# Substitute 2048 for 1024 if you are using
# 2048 bit keys. 
#dh /root/openvpn-test-server/keys/dh1024.pem
dh /root/openvpn-test-server/keys/dh.pem

script-security 2
up do-inetd-ifconfig.sh
#ifconfig 10.204.9.1 255.255.255.0
#ifconfig-ipv6 fd00:abcd:204:9::1/64 fd00:abcd:204:9::2

# peer is down if no ping received during
# a 120 second time period.
#keepalive 60 190
#keepalive 10 30

# Enable compression on the VPN link.
# If you enable it here, you must also
# enable it in the client config file.

comp-lzo

push "route 10.204.0.0 255.255.0.0 10.204.9.1"
push "route-ipv6 fd00:abcd:204::/48"
verb 3

# COMPAT: gert, 13.11.21 compat with 2.2/2.3 clients
tls-version-min 1.0

# COMPAT: gert, 22.12.21, OpenSSL 3.0.0 / sha1 & BF-CBC 
tls-cert-profile insecure
providers legacy default
