#!/bin/sh
#
#
INSTANCES="
tun-tcp-p2mp
tun-udp-p2mp
tun-udp-p2mp-topology-subnet
tap-udp-p2mp
tun-udp-p2mp-112-mask
tun-udp-p2mp-fragment
tun-udp-p2mp-2.3
tun-udp-p2mp-2.3-small
tun-udp-p2mp-2.4
tun-udp-p2mp-2.4-noncp
Xtun-udp-p2mp-ccd-static
Xtun-udp-p2mp-polar
"

cd /root/openvpn-test-server || exit 1
ifconfig lo0 10.194.0.1/32 alias
ifconfig lo0 inet6 fd00:abcd:194:0::1/128 alias

# TAP driver loaded? (TUN autoloads, TAP doesn't)
if kldstat |grep if_tap 
then
    :
else
    kldload if_tap
fi

# accept IPv4 connects on IPv6 socket (workaround limited v2.3 functionality)
sysctl -w net.inet6.ip6.v6only=0

for SI in $INSTANCES
do
    # to avoid starting an instance, just put an "X" before the 
    # directory name in the list above -> skip all non-existing dirs
    if [ ! -d $SI ] ; then continue ; fi

    echo "starting $SI/server.conf..."
    BIN=./openvpn
    if [ -x $SI/openvpn ] ; then BIN="$SI/openvpn" ; fi
    $BIN --daemon $SI --cd $SI --config server.conf \
		--writepid ../openvpn-$SI.pid
 # print config (grep'ed from server.conf)
    sleep 1
done

#
exit 0
