port 51195
proto udp6
dev tun

ca /root/openvpn-test-server/keys/ca.crt
cert /root/openvpn-test-server/keys/server.crt
key /root/openvpn-test-server/keys/server.key
dh /root/openvpn-test-server/keys/dh.pem

# Configure server mode and supply a VPN subnet
# for OpenVPN to draw client addresses from.
# The server will take 10.8.0.1 for itself,
# the rest will be made available to clients.
# Each client will be able to reach the server
# on 10.8.0.1. Comment this line out if you are
# ethernet bridging. See the man page for more info.
server 10.204.3.0 255.255.255.0

# gert, 7.6.20, no ipv6 -> want to test ipv4-only pools
#server-ipv6 fd00:abcd:204:3::/64
topology subnet

# Maintain a record of client <-> virtual IP address
# associations in this file.  If OpenVPN goes down or
# is restarted, reconnecting clients can be assigned
# the same virtual IP address from the pool that was
# previously assigned.
ifconfig-pool-persist ipp.txt 60

# intentionally do not push /16 here, as that would mask failures to
# install the 10.194.<x>.0/24 top subnet route
#push "route 10.204.0.0 255.255.0.0"
push "route 10.204.0.0 255.255.255.0"
push "route 10.204.128.0 255.255.128.0"
push "route-ipv6 fd00:abcd:204::/48"

keepalive 10 30

# gert, 04.05.22, add tls-auth to instance _3 / udp 51195
tls-auth /root/openvpn-test-server/keys/ta3.key

# Enable compression on the VPN link.
# If you enable it here, you must also
# enable it in the client config file.
comp-lzo
# testing 8fa8a17528c0
#  desired for master, harmful for 2.5
#VERSION master
#VERSION !25
#VERSION !24
#V compress migrate
compress migrate

# The maximum number of concurrently connected
# clients we want to allow.
;max-clients 100

# Output a short status file showing
# current connections, truncated
# and rewritten every minute.
status openvpn-status.log

# Set the appropriate level of log
# file verbosity.
#
# 0 is silent, except for fatal errors
# 4 is reasonable for general usage
# 5 and 6 can help to debug connection problems
# 9 is extremely verbose
verb 4

cipher BF-CBC        # Blowfish (for 2.2/2.3 client compat)

# COMPAT: gert, 13.11.21 compat with 2.2/2.3 clients
tls-version-min 1.0
# COMPAT: gert, 13.11.21, add BF-CBC (2.2/2.3 clients)
ncp-ciphers AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305:BF-CBC
# COMPAT, gert, 15.11.21, add fallback cipher (2.3 / --enable small, no OCC)
data-ciphers-fallback BF-CBC

# COMPAT: gert, 22.12.21, OpenSSL 3.0.0 / sha1 & BF-CBC 
tls-cert-profile insecure
providers legacy default
