port 51197
proto udp6
dev tun

ca /root/openvpn-test-server/keys/ca.crt
cert /root/openvpn-test-server/keys/server.crt
key /root/openvpn-test-server/keys/server.key
dh /root/openvpn-test-server/keys/dh.pem

# this is for testing the IPv6-only server side
# (2.3 and 2.4 clients will fail)
server-ipv6 fd00:abcd:204:5::/124

# Maintain a record of client <-> virtual IP address
# associations in this file.  If OpenVPN goes down or
# is restarted, reconnecting clients can be assigned
# the same virtual IP address from the pool that was
# previously assigned.
ifconfig-pool-persist ipp.txt 60

# new default in 2.7 -> this test needs net30 (ipp.txt)
topology net30

# Push routes to the client to allow it
# to reach other private subnets behind
# the server.  Remember that these
# private subnets will also need
# to know to route the OpenVPN client
# address pool (10.8.0.0/255.255.255.0)
# back to the OpenVPN server.
push "route 10.204.0.0 255.255.0.0"
push "route-ipv6 fd00:abcd:204::/48"

keepalive 10 30

# gert, 4.5.22, tls-crypt instance (_5 / 51197)
tls-crypt /root/openvpn-test-server/keys/tc5.key
tls-crypt-v2 /root/openvpn-test-server/keys/tcv2-5-server.key
#tls-crypt-v2-verify /root/t_server/tun-udp-p2mp-112-mask/tls-crypt-v2.sh
tls-crypt-v2-verify /home/rocky/openvpn-tests/t_server/original/t_server/tun-udp-p2mp-112-mask/tls-crypt-v2.sh

# Enable compression on the VPN link.
# If you enable it here, you must also
# enable it in the client config file.
comp-lzo

#client-connect /root/openvpn-test-server/client-connect-switchcomp.sh
client-connect /home/rocky/openvpn-tests/t_server/original/t_server/push-dummy-v4-to-old-clients.sh
script-security 2

# Output a short status file showing
# current connections, truncated
# and rewritten every minute.
status openvpn-status.log

# Set the appropriate level of log
# file verbosity.
#
# 0 is silent, except for fatal errors
# 4 is reasonable for general usage
# 5 and 6 can help to debug connection problems
# 9 is extremely verbose
verb 4

# plugin testeria
setenv verb 8
setenv plugin_cc_config 'push "route-ipv6 fd00:dead:beef::2001/128"'
setenv plugin_cc2_config 'push "route-ipv6 fd00:dead:beef::2002/128"'
plugin /root/openvpn-test-server/plugins/sample-client-connect.so

cipher BF-CBC        # Blowfish (for 2.2/2.3 client compat)

# COMPAT: gert, 13.11.21 compat with 2.2/2.3 clients
tls-version-min 1.0
# COMPAT: gert, 13.11.21, add BF-CBC (2.2/2.3 clients)
ncp-ciphers AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305:BF-CBC
# COMPAT, gert, 15.11.21, add fallback cipher (2.3 / --enable small, no OCC)
data-ciphers-fallback BF-CBC

# COMPAT: gert, 22.12.21, OpenSSL 3.0.0 / sha1 & BF-CBC 
tls-cert-profile insecure
providers legacy default
